exercises = [
    "Barbell Bench Press",
    "Barbell Bent-Over Rows",
    "Barbell Bicep Curls",
    "Barbell Bulgarian Split Squats",
    "Barbell Clean and Jerk",
    "Barbell Close-Grip Bench Press",
    "Barbell Deadlifts",
    "Barbell Decline Bench Press",
    "Barbell Farmer's Walk",
    "Barbell Front Squats",
    "Barbell Glute Bridges",
    "Barbell Good Mornings",
    "Barbell Hack Squats",
    "Barbell Hang Cleans",
    "Barbell Hip Thrusts",
    "Barbell Incline Bench Press",
    "Barbell Landmine Press",
    "Barbell Lunges",
    "Barbell Military Press",
    "Barbell Pendlay Rows",
    "Barbell Power Cleans",
    "Barbell Power Snatches",
    "Barbell Push Press",
    "Barbell Romanian Deadlifts",
    "Barbell Russian Twists",
    "Barbell Shrugs",
    "Barbell Skull Crushers",
    "Barbell Snatch Grip Deadlifts",
    "Barbell Strict Press",
    "Barbell Squats",
    "Barbell Sumo Deadlifts",
    "Barbell Thrusters",
    "Barbell Upright Rows",
    "Barbell Wrist Curls",
    "Barbell Zercher Squats",
    "Barbell 21s (Bicep Curls)",
    "Barbell Bent-Over T-Bar Rows",
    "Barbell Box Squats",
    "Barbell Calf Raises",
    "Barbell Cheat Curls",
    "Barbell Concentration Curls",
    "Barbell Deficit Deadlifts",
    "Barbell Drag Curls",
    "Barbell Face Pulls",
    "Barbell Floor Press",
    "Barbell Hack Squats",
    "Barbell High Pulls",
    "Barbell Jefferson Curls",
    "Barbell One-Arm Snatches",
    "Barbell Rack Pulls",
    "Barbell Turkish Get-Ups",
    "Barbell W-Grip Curls",
    "Barbell Z Press",
    "Dumbbell Bench Press",
    "Dumbbell Bent-Over Rows",
    "Dumbbell Bicep Curls",
    "Dumbbell Bulgarian Split Squats",
    "Dumbbell Clean and Press",
    "Dumbbell Deadlifts",
    "Dumbbell Farmer's Walk",
    "Dumbbell Flyes (Chest Flyes)",
    "Dumbbell Front Raises",
    "Dumbbell Hammer Curls",
    "Dumbbell Incline Bench Press",
    "Dumbbell Lateral Raises",
    "Dumbbell Lunges",
    "Dumbbell Pendlay Rows",
    "Dumbbell Romanian Deadlifts",
    "Dumbbell Shrugs",
    "Dumbbell Side Raises",
    "Dumbbell Skull Crushers",
    "Dumbbell Squats",
    "Dumbbell Sumo Deadlifts",
    "Dumbbell Tricep Extensions",
    "Dumbbell Upright Rows",
    "Dumbbell Wrist Curls",
    "Dumbbell Zercher Squats",
    "Dumbbell 21s (Bicep Curls)",
    "Dumbbell Bent-Over T-Bar Rows",
    "Dumbbell Box Jumps",
    "Dumbbell Calf Raises",
    "Dumbbell Cheat Curls",
    "Dumbbell Concentration Curls",
    "Dumbbell Deficit Deadlifts",
    "Dumbbell Drag Curls",
    "Dumbbell Face Pulls",
    "Dumbbell Floor Press",
    "Dumbbell Hack Squats",
    "Dumbbell High Pulls",
    "Dumbbell Jefferson Curls",
    "Dumbbell One-Arm Snatches",
    "Dumbbell Rack Pulls",
    "Dumbbell Turkish Get-Ups",
    "Dumbbell W-Grip Curls",
    "Dumbbell Windmills",
    "Dumbbell Woodchoppers",
    "Dumbbell Y-Raises",
    "Dumbbell Russian Twists",
    "Dumbbell Sprints",
    "Dumbbell Push Press",
    "Dumbbell Hang Cleans",
    "Dumbbell Push-Ups",
    "Dumbbell Plank Rows",
    "Push-Ups",
    "Pullups",
    "Chinups",
    "Dips",
    "Bodyweight Squats",
    "Lunges",
    "Planks",
    "Burpees",
    "Mountain Climbers",
    "L-Sits",
    "Handstand Push-Ups",
    "Diamond Push-Ups",
    "Wide-Grip Pull-Ups",
    "Close-Grip Push-Ups",
    "Squats Jumps",
    "Pistol Squats",
    "Box Jumps",
    "Wall Sits",
    "Inverted Rows",
    "Hindu Push-Ups",
    "Clap Push-Ups",
    "Mountain Climber Twists",
    "V-Ups",
    "Superman Holds",
    "Hanging Leg Raises",
    "Bicycle Crunches",
    "Plank to Push-Up",
    "Russian Twists",
    "Jumping Lunges",
    "Jumping Jacks",
    "Burpee Pull-Ups",
    "Inchworms",
    "Tuck Jumps",
    "Scissor Kicks",
    "Box Push-Ups",
    "Plank Variations",
    "Hollow Body Holds",
    "Side Planks",
    "Push-Up Variations",
    "Chin-Ups with Knee Raises",
    "Dive Bomber Push-Ups",
    "One-Legged Push-Ups",
    "Sit-Ups",
    "Kettlebell Swings",
    "Wall Handstands",
    "Tuck Planche",
    "Back Bridges",
    "Human Flags",
    "Muscle-Ups",
    "Rope Climbs",
    "Plyometric Push-Ups",
    "Weighted Pull-Ups/Chin-Ups",
    "Weighted Dips",
    "Weighted Push-Ups",
    "Weighted Pistol Squats",
    "Weighted Bulgarian Split Squats",
    "Weighted Planks",
    "Weighted Pullups",
    "Weighted Chinups",
    "Weighted Muscle-Ups",
    "Weighted L-Sits",
    "Weighted Push-Up Variations (e.g., one-arm push-ups with a weight)",
    "Weighted Calisthenics Leg Raises",
    "Weighted Handstand Push-Ups",
    "Weighted Diamond Push-Ups",
    "Weighted Wide-Grip Pull-Ups",
    "Weighted Close-Grip Push-Ups",
    "Weighted Squats Jumps",
    "Weighted Box Jumps",
    "Weighted Wall Sits",
    "Weighted Inverted Rows",
    "Weighted Hindu Push-Ups",
    "Weighted Clap Push-Ups",
    "Weighted Mountain Climber Twists",
    "Weighted V-Ups",
    "Weighted Superman Holds",
    "Weighted Hanging Leg Raises",
    "Weighted Bicycle Crunches"
]
