name: "dev_integration"

on:
  push:
    branches: 
      - 'feature/**'

jobs:
  integrate:
    name: integrate with development
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Merge with development
      run: |
        branch_name="${{ github.ref }}"
        branch_name="${branch_name#refs/heads/}"
        echo "The branch name is $branch_name"